Added Support for MongoDB
ahnaf-zamil/fastapi-server-session pull request #1
Opened 2022-02-13 07:15 UTC by iudeen

2022-02-15 16:59 UTC, ahnaf-zamil commented
Thanks a lot for making this PR. I will take a look at this soon.

2022-02-17 15:18 UTC, ahnaf-zamil requested changes

2022-02-17 15:18 UTC, ahnaf-zamil commented on fastapi_server_session/interfaces/mongo.py
> +# Copyright (c) 2022 iudeen
Need to change the copyright to my name since I own the project, but you can add yourself in an "Author" section below the copyright.

```py
# Author: iudeen
```

2022-02-18 06:00 UTC, iudeen reviewed
Made necessary changes

2022-02-18 13:21 UTC, ahnaf-zamil approved these changes

2022-02-18 13:21 UTC, merged